- src/YouTubeDownload.py
-job.name название слишком обрезано.Может стоит увеличить количество
букв названия?
> add missing import

- po/fi.po
- po/nl.po
> Translations update

- po/pt.po
Based in Regenerate language files after remove history and watch later ( YouTube.pot )
> Update portuguese pt.po translation

- src/YouTubeVideoUrl.py
from ytdl.org
this commit https://github.com/ytdl-org/youtube-dl/commit/c3cfea906869e8358652e382679a5996c2aec73e
> Fix sigfunc name extraction

- po/YouTube.pot
- po/bg.po
- po/cs.po
- po/de.po
- po/el.po
- po/es.po
- po/et.po
- po/fi.po
- po/fr.po
- po/hu.po
- po/id.po
- po/it.po
- po/lv.po
- po/nl.po
- po/pl.po
- po/pt.po
- po/ru.po
- po/sk.po
- po/tr.po
- po/uk.po
> Update language files

- src/YouTubeUi.py
Optimize variables and functions
> Refactor YouTubeMain

- .github/workflows/ci.yml
- test/try_plugin.py
To test plugin also on old OpenPLi image versions
force-tests skip-release
> Add in tests OpenPLi release-6.2 enigma

- .github/workflows/ci.yml
- sonar-project.properties
I took the idea to use sonarcloud from openatv, thx jbleyel.
skip-release
> Add SonarCloud workflow action

- sonar-project.properties
To disable failed status report
> Try disable file coverage calculation

- .github/workflows/ci.yml
- sonar-project.properties
- test/try_plugin.py
> Add code coverage on OpenPLi develop GUI test

- test/try_plugin.py
> Add tests for YouTubePlayer methods to increase code coverage

- .github/workflows/ci.yml
> Fix test on OpenViX Developer

- .github/workflows/ci.yml
> Fix test on openatv 7

- .github/workflows/ci.yml
> Switch to openatv 7.1 for test

- .github/workflows/ci.yml
> Fix test on OpenPLi develop

- .github/workflows/ci.yml
> Change deprecating set-output in ci checks

- .github/workflows/automerge.yml
- .github/workflows/ci.yml
It looks like marceloprado/has-changed-path has not been maintained for a long time.
force-test skip-release
> Change has-changed-path action to paths-filter

- test/enigma.py
> Fix test on openatv 7.1

- .github/workflows/ci.yml
- sonar-project.properties
> Use python 3.11 in code tests

- test/enigma.py
> Decrease enigma test file

- src/YouTubeApi.py
- src/YouTubeDownload.py
- src/YouTubeSearch.py
- src/YouTubeUi.py
- src/plugin.py
- test/test_plugin.py
> Rename some clases, parameters and local variables

- test/try_plugin.py
> Improve DownloadTask code coverage

- test/try_plugin.py
> Test embedded skins in all resolutions

- test/try_plugin.py
> Fix test if active job not exist

- test/enigmahelper.py
> Fix test on openatv

- src/jsinterp.py
> Remove the unused function parameter in jsinterp

- .github/workflows/ci.yml
After https://github.com/OpenViX/enigma2/commit/1e80c52a959534784c083ae7c6525089fa4b64ea
force-test skip-release
> Fix test on OpenViX

- .github/workflows/automerge.yml
- .github/workflows/ci.yml
> Fix Node.js 16 deprecated warnings in workflows

- .github/workflows/ci.yml
> Change python version from 3.11 to 3.12

- src/YouTubeVideoUrl.py
Move nested conditional expression into an independent statement.
> Fix code smell in YouTubeVideoUrl

- test/enigmahelper.py
> Fix test on OpenAtv again

- src/jsinterp.py
To perform additional checks and show error reasons in log.
> Implement assertion function in jsinterp

- .github/workflows/ci.yml
> Fix python 2.7 in workflows

- .github/workflows/ci.yml
- test/test_plugin.py
> Use ubuntu-22.04 in workflows to install python2

- test/test_plugin.py
> Ignore most viewed test error if it fails

- src/YouTubeVideoUrl.py
Sorts the available urls according to preference and then selects in order from the list to retrieve the url even if a specified condition is not met.
> Refactors the url fetching logic in YouTubeVideoUrl

- .github/workflows/ci.yml
> Use OpenPLi release-9.1 in tests

- src/jsinterp.py
> Fix code smells in jsinterp

- .github/workflows/ci.yml
- test/test_plugin.py
> Fix workflow test on OpenViX
